language: node_js
branches:
  only:
  - travis-test
# addons:
#   apt:
#     packages:
#     - sshpass
before_script:
- echo -e "Host rocket.chat\n\tHostName rocket.chat\n\tUser github\n\tIdentityFile ~/.ssh/id_rsa\n" >> ~/.ssh/config
script:
# - gulp deploy
- echo "skip"
- cat ~/.ssh/id_rsa
- cat ~/.ssh/id_rsa.pub
after_success:
# - tar -czf package.tgz build
# - export SSHPASS=$DEPLOY_PASS
- echo $DEPLOY_USER
- echo $DEPLOY_HOST
- echo $DEPLOY_PATH
# - sshpass -e scp package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
- ssh -o "StrictHostKeyChecking no" $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh
env:
  global:
  - secure: V9dhhCGT7vPCh3X/+d5NOhUMGH5AxnjjMofg4ld+9Pi/zJuvldnj1dVo9DD9oR70sNrhhNcPajQ5Bs5X732RXFIUGNv0aykmsEj+TRs53Xd0v7+ZlOWN8NyajCAowaVl+hU4lCbvVqvaffmWAa6p6Xmvzn/1K2nshZ+Fyy+XTEOBn81JHlbIc6FgVTsUaBpFxfjSwSSFIad/id5/owoYcYXVkO3ZIsueKjgOTqkDbU2/FL+/zY0N6FAKrkOoLRx5CIff7sVUUIH3+rf9l5051Glh3TE5hGHiZzLXg908QbOZzFG5oc3yXGvNbVJWt47J1NB0HlYLilqqwhBVUaEBaJTNQKhICkNnKj51N1O1ErAUkYMid7C9ynqeTKu3HXxvwUGQ2EKFZnTbL+Nd2i8ZcS7lWc4dYcUFfndIR8W+2WqoYF9IOFtfx5r8aTKS0wG7WOCMcqhvjD1bLrnTX1RbuRxw2tNee7M/bSLzDnf2zugbjFnhFLnGkduOFXrGpA4tAaaG4zZDZa1A6vIkSjQBMKMnotjXAMkdsAzbSUdzgZ1XzbKd8fa6gsV6GURRwQvSfoJ6UoKgb4x8S5yr/ze/r6R9JQ+kwJZ40UPoy9eEIpBZJTh33rSFPIOyYoSe5tQ+WZxFK0s4ciYh0VGy0UglCCc5JolpHhpqapfQQadh4ss=
  - secure: GqULfcboftQa8KF8FBtLgAq76653A6kDjGd+KCADLAo8BxkRfyTPmxuAIjVDYGj+sbmjkz49we9jHdg0pP4MxDZVhlr5iyZVzDhGzWQhqVg14mDHwlLX6KT/V8mKoUjqsgn0UhGog2z1/h3XCXJwoDuA9Uhhru+kMbVMON5yAaQLldjOHkOxAALP6N7p+e3zt9WlIFS7LsfTCcO+oe0Wyq6Xs90uPmC1NuAr8Pg1RkNMdcoUeJ/9YgdBpTG/sINJllnhNnHEiVFd3JHpkhwkQ7VmRGCuI6wxg9vOHS6JEoykR4X/VlktYLnvHFF8RoR6GxMRExGvvApsVI4W5YnWlXGNLKd1FwJuSJWd6tNd8sCmGGfqecU2csQ8N7km6WnWkHyBGAqsOqn6TZkXv4yzxmZvTyaTwAbPz/JwSaW2RyooRp/r0jL7fh+QsRJzSY7hKu0Ae+Vfg6LoG/KwhIFaaDFPxLd5ca2CBRVQLUGeUz4ICMZ7sTr4dSb54iG2QD/svdPwUSe6t3z+07Zt2nnAGUfCa4/u1cvyvRDoVL8POqobpiHftjxg3PqIiEqgnR352XvmjisNIbnZnzcSoVilU1ClwTcRuhSj/1CpBSJC9LC2/ks36kDLKewtw1mH5iHE7kYGueRO7pe6r5wX5jrVvSCzD+i4LRqDtx1wkEElutE=
  - secure: KssPuaMlPZQ/sJFIms1byyodsyJX9PziUSP8l5Qz2fzqj+fiEItjxcW/ZVHC0b0KmAv6CHr2IhhjiR7HkxFXYPbRNxg6A1UI6PxndO7uUYTaNtHyVmMKH/Dd4tKbb/4zKmv1A2+IVTFc2dcldOn8SBpLA73Zfp9sAnTBJg0iWC7PfTTwtf6OK3RzGx1UJhUDT0VIzNw4kpqDYxipdSVQqSNx0Zn3uX96Z5vMR9A3MtUvZo/acmkXVwnDMWzTHiEZiCa3sVmfWMlAh2kUZ25TEF2Hez38Z1FYVQfQZIi4FBTdJ5f0hekD6/M2U8oRbw8CV8dXlFoWXUngH1JUTrto0Kusz4GCMqYoKC+rZasD13NHsf7t8cQVFumSZyyDBXHvLWmZegdIAZW+i5zzHYEL3hozXZ2e7cwqjHaqoGnIvxqaLHpDPQ+PU0dxuuCkSLH0KWsTuqp+0uSDz0eRjVCbsHhNT1s0wXNVIZWjlWQGSwfmdoUBP4sirYuSGbYB4pjYsm52maaE1MW5S+Cx5WwW0x1/pleuRGzCZCefQxWL6I6l8jrNEX6hYkLh8a5wcn32pWPmMad+VQsaiyhnyGZU1UQhB8NckDNKTAl0cZ8V8FUAiJGPRqJ6deCwX6CgMjueffzDdn0wpTUBztlW0dp0t4Hx/7Q17W2VrdBc1wdi2j4=
  - secure: dfky1VcE/N5kn9gPAh8m6ACdtDKtg3NeVfQQsbotzs358Q/7OmckwyUjnMdo+0EFRHel0Fpuej9ek425H2mLN4v90fLRdBPoMvfnQnGk2bwf2VLSfIovRAtvtOy4phHUcUl1pmuvMVvL+kW9uusVv+oj9HcuwyppHYEpTNgJg0cKWZrTDJtpv1CdTc1ymew5yoBuejpQ5gED1OkSIs9199miK98eycpeRT9QzZseH+olMbwoUOGhpvgkM2jOzXW+GNWEV7U8sCjZK1xq/L8wffxcs6/9M03wiQqdORvVon+CWr/uJFq39Mz+cQkWyCez+z6vLeSyeFZ7U8o5RqYzl3YpYRyRwjYFpPMccpVQo9tZpPCdypscT4lD6ThxkVm/FUnYJm56POLoNrwH5LzeZO6Njy4kGWxLEkEaugQE7lVBCWcyo08ngh3IHl3c+raHYEjw93litsyIc2RO2ny6m0L1GJHbIZOBqibzxT5tr0Opm94p/VjJAH47LBxanaFjlf0Y4PPhDobWIslzIcO/8kzZHqw3GUw+t41mTziweiQeg7CMjlC3EUTeMQoqgtsIyCioktXmNLTxUqz04ISFIGpPvBE+jr2FA+Ko18KXONtCKMHISKdY0RWQ1O6RDpdHq6PxZygsUNEJQR91L5xkbjgNGzBezPipaXVx5gxZ+P4=
